backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: jerv/robertgsalazar # owner/repo
  
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "doctor" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Doctor" # Used in the UI, ie.: "New Post"
    folder: "content/doctors"
    slug: "{{slug}}"
    # extension: "yml"
    # format: "yml"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "Doctor"}
  - label: "Pain Pages"
    name: "pain-pages"
    files:
      - label: "Pharma Page"
        name: "pharma"
        file: "content/pharma.yml"
        fields:
          - {label: Intro, name: intro, widget: markdown}
          - {label: Left Paragraph, name: left-para, widget: markdown}
          - {label: Right Paragraph, name: right-para, widget: markdown}
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "site/content/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}